trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  ARM_TEMPLATE: 'ARM/Simple_Vnet_ARM.json'  # Path to your ARM template
  RESOURCE_GROUP: 'Training'  # Replace with your Azure Resource Group name
  LOCATION: 'Central India'  # Replace with your preferred Azure region
  system.debug: true

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure'
    subscriptionId: '254fc39b-c667-436b-80a7-f0dc7038e484'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'Training'
    location: 'Central India'
    templateLocation: 'Linked artifact'
    csmFile: 'ARM/Simple_Vnet_ARM.json'
    deploymentMode: 'Incremental'
