trigger:
- main  # Trigger pipeline on changes to the main branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  tf_source: 'Terraform/Vnet_eg_with_variable-1'  # Path to the Terraform configuration
  tf_backend_storage_account: 'azurepipelinestoacc'  # Replace with your Storage Account Name
  tf_backend_container: 'diape'  # Replace with your Blob Container Name
  tf_backend_key: 'vnet.terraform.tfstate'  # Replace with your state file name
  resource_group: 'Training'  # Replace with your Resource Group Name

steps:
# Step 1: Install Terraform
# - task: ms-devlabs.custom-terraform-tasks.custom-terraform-installer-task.TerraformInstaller@2
#   inputs:
#     terraformVersion: 'latest'

- script: |
    curl -sSL https://releases.hashicorp.com/terraform/1.5.6/terraform_1.5.6_linux_amd64.zip -o terraform.zip
    unzip terraform.zip
    sudo mv terraform /usr/local/bin/
  displayName: 'Install Terraform'
  
# Step 2: Initialize Terraform
- script: |
    terraform init \
      -backend-config="storage_account_name=$(tf_backend_storage_account)" \
      -backend-config="container_name=$(tf_backend_container)" \
      -backend-config="key=$(tf_backend_key)" \
      -backend-config="resource_group_name=$(resource_group)"
  displayName: 'Terraform Init'
  workingDirectory: $(tf_source)


# Step 3: Validate Terraform Configuration
- script: |
    terraform validate
  displayName: 'Terraform Validate'
  workingDirectory: $(tf_source)

# # Step 4: Plan Terraform Deployment
# - script: |
#     terraform plan -out=tfplan
#   displayName: 'Terraform Plan'
#   workingDirectory: $(tf_source)

# - task: TerraformTaskV4@4
#   inputs:
#     provider: 'azurerm'
#     command: 'apply'
#     environmentServiceNameAzureRM: 'Azure'

# Step 5: Apply Terraform Deployment
- script: |
    terraform apply -auto-approve
  displayName: 'Terraform Apply'
  workingDirectory: $(tf_source)


# Note
# Configure the Terraform Main.tf file Azure Provider like below
# provider "azurerm" {
#   features {}
#   subscription_id = "2542fb-c6627-4326b-802a7-f0d03e484"
#   client_id       = "44242f8-0027f-41270-928fc-49e2860ab"  # Replace with your Service Principal's Client ID
#   client_secret   = "DGL28Q~spf82eEyliTync212c4p"  # Replace with your Service Principal's Client Secret
#   tenant_id       = "c917-7207-42628-aafe-ef8a30"  # Replace with your Azure Tenant ID
# }

