trigger:
- main  # Or specify the branch you want to trigger the pipeline

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: TerraformToolInstaller@0
  inputs:
    terraformVersion: 'latest'

- script: |
    terraform init
    terraform plan -out=tfplan
  displayName: 'Terraform Init and Plan'
  workingDirectory: '$(System.DefaultWorkingDirectory)/Terraform/vnet-example.tf'

- task: TerraformTaskV1@0
  inputs:
    provider: 'azurerm'
    command: 'apply'
    workingDirectory: '(System.DefaultWorkingDirectory)/Terraform/vnet-example.tf'
    environmentServiceNameAzureRM: 'MY_Azure_SC'
    commandOptions: '-auto-approve -input=true'
